In [3]:
import pandas as pd

In [4]:
df2017 = pd.read_excel("./2017.xlsx")
df2017.iloc[:,:4]=df2017.iloc[:,:4].fillna(method="ffill")
df2017[["조회년도","조회월"]]=df2017[["조회년도","조회월"]].astype("int")
df2017

,조회년도,조회월,항만명,입출항구분,Measures,합계,육 류,어패류.갑각류 등,양 곡,제분공업 생산품,...,목재.목탄.코르크 등,방직용섬유 및 그제품,고 철,철강 및 그제품,비철금속 및 그제품,기계류 및 그부품,전기기기 및 그부품,차량 및 그부품,항공기.선박 및 부품,기 타
0,2017,1,부산,입항,국적선,920459,354.0,6943.0,0.0,0.0,...,3399.0,329669.0,395.0,74549.0,11935.0,178715.0,128640.0,7417.0,3645.0,72683.0
1,2017,1,부산,입항,외국선,4906600,117053.0,83217.0,97497.0,18384.0,...,181123.0,974037.0,23684.0,480113.0,235133.0,270098.0,377342.0,91775.0,28920.0,496809.0
2,2017,1,부산,입항,수출입계,5827059,117407.0,90160.0,97497.0,18384.0,...,184522.0,1303706.0,24079.0,554662.0,247068.0,448813.0,505982.0,99192.0,32565.0,569492.0
3,2017,1,부산,입항,연안선,983620,0.0,0.0,0.0,0.0,...,10.0,20046.0,0.0,48426.0,0.0,0.0,0.0,15293.0,0.0,1.0
4,2017,1,부산,입항,총계,6810679,117407.0,90160.0,97497.0,18384.0,...,184532.0,1323752.0,24079.0,603088.0,247068.0,448813.0,505982.0,114485.0,32565.0,569493.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,2017,12,울산,출항환적,국적선,11010,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,1537.0,NaN,NaN,NaN,4679.0,NaN,586.0
956,2017,12,울산,출항환적,외국선,72034,NaN,NaN,NaN,NaN,...,NaN,164.0,NaN,698.0,NaN,NaN,NaN,48718.0,NaN,367.0
957,2017,12,울산,출항환적,수출입계,83044,NaN,NaN,NaN,NaN,...,NaN,164.0,NaN,2235.0,NaN,NaN,NaN,53397.0,NaN,953.0
958,2017,12,울산,출항환적,연안선,0,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,0.0,NaN,NaN,NaN,0.0,NaN,0.0
959,2017,12,울산,출항환적,총계,83044,NaN,NaN,NaN,NaN,...,NaN,164.0,NaN,2235.0,NaN,NaN,NaN,53397.0,NaN,953.0

In [5]:
df2018 = pd.read_excel("./2018.xlsx")
df2018.iloc[:,:4]=df2018.iloc[:,:4].fillna(method="ffill")
df2018[["조회년도","조회월"]]=df2018[["조회년도","조회월"]].astype("int")
df2018

,조회년도,조회월,항만명,입출항구분,Measures,합계,육 류,어패류.갑각류 등,양 곡,제분공업 생산품,...,목재.목탄.코르크 등,방직용섬유 및 그제품,고 철,철강 및 그제품,비철금속 및 그제품,기계류 및 그부품,전기기기 및 그부품,차량 및 그부품,항공기.선박 및 부품,기 타
0,2018,1,부산,입항,국적선,893330,1843.0,8217.0,1131.0,150.0,...,8297.0,366007.0,235.0,78110.0,12187.0,71975.0,159366.0,5022.0,2601.0,70421.0
1,2018,1,부산,입항,외국선,4885390,93578.0,89771.0,138721.0,20720.0,...,140332.0,931452.0,30257.0,304451.0,242606.0,300465.0,386273.0,89181.0,21340.0,522293.0
2,2018,1,부산,입항,수출입계,5778720,95421.0,97988.0,139852.0,20870.0,...,148629.0,1297459.0,30492.0,382561.0,254793.0,372440.0,545639.0,94203.0,23941.0,592714.0
3,2018,1,부산,입항,연안선,788173,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,44448.0,0.0,0.0,0.0,12768.0,0.0,0.0
4,2018,1,부산,입항,총계,6566893,95421.0,97988.0,139852.0,20870.0,...,148629.0,1297459.0,30492.0,427009.0,254793.0,372440.0,545639.0,106971.0,23941.0,592714.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,2018,12,울산,출항환적,국적선,4913,NaN,NaN,NaN,NaN,...,NaN,193.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,1866.0
956,2018,12,울산,출항환적,외국선,96092,NaN,NaN,NaN,NaN,...,NaN,2348.0,NaN,NaN,NaN,15.0,NaN,10593.0,NaN,766.0
957,2018,12,울산,출항환적,수출입계,101005,NaN,NaN,NaN,NaN,...,NaN,2541.0,NaN,NaN,NaN,15.0,NaN,10593.0,NaN,2632.0
958,2018,12,울산,출항환적,연안선,0,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0
959,2018,12,울산,출항환적,총계,101005,NaN,NaN,NaN,NaN,...,NaN,2541.0,NaN,NaN,NaN,15.0,NaN,10593.0,NaN,2632.0

In [6]:
df2019 = pd.read_excel("./2019.xlsx")
df2019.iloc[:,:4]=df2019.iloc[:,:4].fillna(method="ffill")
df2019[["조회년도","조회월"]]=df2019[["조회년도","조회월"]].astype("int")
df2019

,조회년도,조회월,항만명,입출항구분,Measures,합계,육 류,어패류.갑각류 등,양 곡,제분공업 생산품,...,목재.목탄.코르크 등,방직용섬유 및 그제품,고 철,철강 및 그제품,비철금속 및 그제품,기계류 및 그부품,전기기기 및 그부품,차량 및 그부품,항공기.선박 및 부품,기 타
0,2019,1,부산,입항,국적선,871864,388.0,11588.0,1318.0,339.0,...,10153.0,311093.0,0.0,72275.0,19195.0,67689.0,162319.0,8772,308.0,60619.0
1,2019,1,부산,입항,외국선,6337651,132974.0,93771.0,145375.0,14503.0,...,219412.0,1064308.0,27277.0,430958.0,246951.0,302859.0,408525.0,834845,37714.0,629224.0
2,2019,1,부산,입항,수출입계,7209515,133362.0,105359.0,146693.0,14842.0,...,229565.0,1375401.0,27277.0,503233.0,266146.0,370548.0,570844.0,843617,38022.0,689843.0
3,2019,1,부산,입항,연안선,1275254,0.0,0.0,0.0,0.0,...,0.0,0.0,5884.0,44584.0,0.0,1123.0,0.0,13086,0.0,0.0
4,2019,1,부산,입항,총계,8484769,133362.0,105359.0,146693.0,14842.0,...,229565.0,1375401.0,33161.0,547817.0,266146.0,371671.0,570844.0,856703,38022.0,689843.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,2019,12,울산,출항환적,국적선,23186,NaN,NaN,NaN,NaN,...,NaN,17.0,NaN,NaN,NaN,NaN,NaN,10734,NaN,63.0
956,2019,12,울산,출항환적,외국선,91005,NaN,NaN,NaN,NaN,...,NaN,2747.0,NaN,NaN,NaN,NaN,NaN,25556,NaN,1603.0
957,2019,12,울산,출항환적,수출입계,114191,NaN,NaN,NaN,NaN,...,NaN,2764.0,NaN,NaN,NaN,NaN,NaN,36290,NaN,1666.0
958,2019,12,울산,출항환적,연안선,0,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,0.0
959,2019,12,울산,출항환적,총계,114191,NaN,NaN,NaN,NaN,...,NaN,2764.0,NaN,NaN,NaN,NaN,NaN,36290,NaN,1666.0

In [7]:
df2020 = pd.read_excel("./2020.xlsx")
df2020.iloc[:,:4]=df2020.iloc[:,:4].fillna(method="ffill")
df2020[["조회년도","조회월"]]=df2020[["조회년도","조회월"]].astype("int")
df2020

,조회년도,조회월,항만명,입출항구분,Measures,합계,육 류,어패류.갑각류 등,양 곡,제분공업 생산품,...,목재.목탄.코르크 등,방직용섬유 및 그제품,고 철,철강 및 그제품,비철금속 및 그제품,기계류 및 그부품,전기기기 및 그부품,차량 및 그부품,항공기.선박 및 부품,기 타
0,2020,1,부산,입항,국적선,887066,760.0,10606.0,177.0,454.0,...,13151.0,328177.0,1443.0,66188.0,22181.0,49467.0,164514.0,12352,7024.0,61914.0
1,2020,1,부산,입항,외국선,4584161,114337.0,59479.0,113322.0,12555.0,...,181403.0,995012.0,22521.0,293974.0,287286.0,237914.0,350333.0,103910,15107.0,349008.0
2,2020,1,부산,입항,수출입계,5471227,115097.0,70085.0,113499.0,13009.0,...,194554.0,1323189.0,23964.0,360162.0,309467.0,287381.0,514847.0,116262,22131.0,410922.0
3,2020,1,부산,입항,연안선,840204,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,68340.0,0.0,0.0,0.0,9340,0.0,0.0
4,2020,1,부산,입항,총계,6311431,115097.0,70085.0,113499.0,13009.0,...,194554.0,1323189.0,23964.0,428502.0,309467.0,287381.0,514847.0,125602,22131.0,410922.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,2020,12,울산,출항환적,국적선,9438,NaN,57.0,NaN,NaN,...,47.0,160.0,NaN,0.0,NaN,0.0,207.0,18,NaN,942.0
956,2020,12,울산,출항환적,외국선,92640,NaN,0.0,NaN,NaN,...,0.0,223.0,NaN,17.0,NaN,541.0,0.0,9388,NaN,1775.0
957,2020,12,울산,출항환적,수출입계,102078,NaN,57.0,NaN,NaN,...,47.0,383.0,NaN,17.0,NaN,541.0,207.0,9406,NaN,2717.0
958,2020,12,울산,출항환적,연안선,0,NaN,0.0,NaN,NaN,...,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0,NaN,0.0
959,2020,12,울산,출항환적,총계,102078,NaN,57.0,NaN,NaN,...,47.0,383.0,NaN,17.0,NaN,541.0,207.0,9406,NaN,2717.0

In [8]:
df2021 = pd.read_excel("./2021.xlsx")
df2021.iloc[:,:4]=df2021.iloc[:,:4].fillna(method="ffill")
df2021[["조회년도","조회월"]]=df2021[["조회년도","조회월"]].astype("int")
df2021

,조회년도,조회월,항만명,입출항구분,Measures,합계,육 류,어패류.갑각류 등,양 곡,제분공업 생산품,...,목재.목탄.코르크 등,방직용섬유 및 그제품,고 철,철강 및 그제품,비철금속 및 그제품,기계류 및 그부품,전기기기 및 그부품,차량 및 그부품,항공기.선박 및 부품,기 타
0,2021,1,부산,입항,국적선,919845,2534.0,12923.0,1195.0,1193.0,...,17608.0,347965.0,1739.0,51175.0,21509.0,50576.0,170039.0,9633,2819.0,58735.0
1,2021,1,부산,입항,외국선,4636555,113476.0,128390.0,41150.0,15568.0,...,154184.0,1082260.0,19427.0,304891.0,297048.0,237612.0,351925.0,109818,10945.0,370548.0
2,2021,1,부산,입항,수출입계,5556400,116010.0,141313.0,42345.0,16761.0,...,171792.0,1430225.0,21166.0,356066.0,318557.0,288188.0,521964.0,119451,13764.0,429283.0
3,2021,1,부산,입항,연안선,878844,0.0,0.0,0.0,0.0,...,0.0,0.0,800.0,71597.0,0.0,0.0,0.0,14925,0.0,0.0
4,2021,1,부산,입항,총계,6435244,116010.0,141313.0,42345.0,16761.0,...,171792.0,1430225.0,21966.0,427663.0,318557.0,288188.0,521964.0,134376,13764.0,429283.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,2021,12,울산,출항환적,국적선,7460,NaN,NaN,NaN,NaN,...,35.0,64.0,NaN,0.0,NaN,NaN,NaN,0,NaN,1709.0
956,2021,12,울산,출항환적,외국선,124435,NaN,NaN,NaN,NaN,...,547.0,217.0,NaN,232.0,NaN,NaN,NaN,4552,NaN,3345.0
957,2021,12,울산,출항환적,수출입계,131895,NaN,NaN,NaN,NaN,...,582.0,281.0,NaN,232.0,NaN,NaN,NaN,4552,NaN,5054.0
958,2021,12,울산,출항환적,연안선,0,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0,NaN,0.0
959,2021,12,울산,출항환적,총계,131895,NaN,NaN,NaN,NaN,...,582.0,281.0,NaN,232.0,NaN,NaN,NaN,4552,NaN,5054.0

In [9]:
result = pd.concat([df2017,df2018,df2019,df2020,df2021])
result.to_csv("result.csv", encoding="utf-8",index=False)

In [10]:
result=result.fillna(0)

In [11]:
result.to_csv("result.csv", encoding="utf-8",index=False)

In [13]:
result.to_excel("result.xlsx", encoding="utf-8",index=False)